name: Build and deploy

on:
  workflow_call:
    secrets:
      role_arn:
        required: true
      artifact_bucket:
        required: true
      # ecr_repository_test:
      #   required: true
      # ecr_repository_traffic_test:
      #   required: true
      # container_sign_kms_key:
      #   required: true
      signing_profile:
        required: true
      # environment:
      #   required: true
      # dynatrace_paas_token:
      #   required: true
    inputs:
      region:
        required: false
        type: string
        default: eu-west-2

permissions:
  id-token: write
  contents: read

jobs:
  # test-images-build-and-push:
  #   name: Build and push test images
  #   runs-on: ubuntu-latest
  #   env:
  #     AWS_REGION: eu-west-2
  #     ENVIRONMENT: ${{ secrets.environment }}
  # is this needed?
  # could these run in paralell?
  # steps:
  # why ?
  # - name: Login to Dynatrace Container Registry
  #   uses: docker/login-action@v4
  #   with:
  #     registry: khw46367.live.dynatrace.com
  #     username: khw46367
  #     password: ${{ secrets.dynatrace_paas_token }}

  # # this checkouts, sets up AWS creds and logs into docker registry
  # - name: Test image build and push
  #   uses: uses: govuk-one-login/devplatform-upload-action-ecr@v1.5.0
  #   with:
  #     role-to-assume-arn: ${{ secrets.role_arn }}
  #     build-and-push-image-only: true
  #     working-directory: test
  #     artifact-bucket-name: "" # ? shouldnt that be optional?
  #     ecr-repo-name: ${{ secrets.ecr_repository_test }}
  #     push-latest-tag: true
  #     container-sign-kms-key-arn: ${{ secrets.container_sign_kms_key }} # ?

  # # this checkouts, sets up AWS creds and logs into docker registry
  # - name: Traffic test image build and push
  #   uses: uses: govuk-one-login/devplatform-upload-action-ecr@v1.5.0
  #   with:
  #     role-to-assume-arn: ${{ secrets.role_arn }}
  #     build-and-push-image-only: true
  #     working-directory: test
  #     artifact-bucket-name: "" # ? shouldnt that be optional?
  #     ecr-repo-name: ${{ secrets.ecr_repository_traffic_test }}
  #     dockerfile: Dockerfile-traffictest # think about name
  #     push-latest-tag: true # ?
  #     container-sign-kms-key-arn: ${{ secrets.container_sign_kms_key }} # ?
  # UNCOMMENT LAST in case cosign blocks ^
  # hopefully can run pipeline without test images - might have to change terraform for build?
  # hasn't blocked front though - whats the difference?

  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest
    # needs: test-images-build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.role_arn }}
          aws-region: ${{ inputs.region }}

      - name: SAM validate
        run: sam validate --region ${{ inputs.region }} -t deploy/template.yaml --lint

      - name: SAM build
        run: |
          mkdir out
          sam build -t deploy/template.yaml --region ${{ inputs.region }} -b out/

      - name: SAM Deploy
        # concurrency and cancel in progress false
        uses: govuk-one-login/devplatform-upload-action@v3.13.0
        with:
          aws-role-arn: ${{ secrets.role_arn}}
          artifact-bucket-name: ${{ secrets.artifact_bucket }}
          signing-profile-name: ${{ secrets.signing_profile }}
          working-directory: ./out
