name: Check PR

on: pull_request
permissions: {}

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    continue-on-error: true
    concurrency:
      group: pre-commit-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Run pre-commit
        uses: govuk-one-login/github-actions/code-quality/run-pre-commit@0c5c351ec34f813b37ecb5c3413e49ccab534c58
        with:
          all-files: true
        env:
          # Skip eslint and prettier as they're covered by ts-style-check job
          SKIP: eslint,prettier

  vite-build-check:
    name: Run vite build check
    needs: pre-commit
    uses: ./.github/workflows/run-vite-build-check.yml

  ts-style-check:
    name: Run typescript style check
    needs: pre-commit
    uses: ./.github/workflows/run-ts-style-check.yml

  unit-tests:
    name: Run Unit tests
    needs: pre-commit
    uses: ./.github/workflows/run-unit-tests.yml

  sonar-scan:
    name: Sonar Scan
    needs: unit-tests
    uses: ./.github/workflows/run-sonar-scan.yml
    secrets:
      github-token: ${{ secrets.github-token }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
