name: Deploy preview

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      role_arn:
        required: true
      bucket_name:
        required: true
    outputs:
      stack-name:
        value: ${{ jobs.deploy-preview.outputs.stack-name }}
      aws-region:
        value: ${{ jobs.deploy-preview.outputs.aws-region}}
      # sha-short:
      #   value: ${{ jobs.build-preview.outputs.sha-short }}

permissions: {}

jobs:
  build-preview:
    name: Build app
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    # concurrency:
    #   group: build-development-${{ github.head_ref || github.ref_name }}
    outputs:
      sha-short: ${{ steps.get-sha.outputs.sha-short }}
    steps:
      - name: Get short SHA
        id: get-sha
        run: echo "sha-short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build app
        uses: govuk-one-login/github-actions/sam/build-application@c35aa8daed14bd1b102f6c55afdf77eaeb958954
        with:
          template: deploy/template.yaml
          cache-name: ipv-cri-ob-api-${{ steps.get-sha.outputs.sha-short }}
          role-to-assume-arn: ${{ secrets.role_arn }}
          pull-repository: true

  deploy-preview:
    name: Deploy stack
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      # contents: read
    timeout-minutes: 15
    needs: build-preview
    # concurrency:
    #   group: deploy-development-${{ github.head_ref || github.ref_name }}
    # environment: development
    outputs:
      aws-region: ${{ steps.deploy-preview.outputs.aws-region }}
      stack-name: ${{ steps.deploy-preview.outputs.stack-name }}
    steps:
      - name: Deploy stack
        uses: govuk-one-login/github-actions/sam/deploy-stack@c35aa8daed14bd1b102f6c55afdf77eaeb958954
        id: deploy
        with:
          aws-role-arn: ${{ secrets.role_arn }}
          s3-prefix: preview
          sam-deployment-bucket: ${{ secrets.bucket_name }}
          stack-name: preview-${{ needs.build-preview.outputs.sha-short}}
          cache-name: ipv-cri-ob-api-${{ needs.build-preview.outputs.sha-short}}
          delete-failed-stack: true
          # do we want disable rollback? I reckon so...

          tags: |
            cri:component=ipv-cri-ob-api
            cri:stack-type=preview
            cri:application=Lime
            cri:deployment-source=github-actions
          parameters: |
            DeploymentType=not-pipeline
            Environment=dev
            ParameterPrefix="ipv-cri-ob-api"

# becuase this has one step - I think I can get rid and just do uses?
