name: Deploy branch to dev
on:
  workflow_dispatch:
  pull_request: # temp

jobs:
  deploy-dev:
    name: Deploy to dev
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_secure-pipeline-deploy.yml
    secrets:
      role_arn: ${{ secrets.DEV_GHA_ROLE_ARN }}
      artifact_bucket: ${{ secrets.DEV_ARTIFACT_BUCKET }}
      # ecr_repository_test: ${{ secrets.DEV_TEST_ECR_REPOSITORY }}
      # ecr_repository_traffic_test: ${{ secrets.DEV_TRAFFIC_TEST_ECR_REPOSITORY }}
      # container_sign_kms_key: $ {{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      signing_profile: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
      # environment: development
      # dynatrace_paas_token: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
