name: Post merge

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: unit-tests-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    steps:
      - name: Setup Node
        uses: govuk-one-login/github-actions/node/install-dependencies@4c76410195b5fcb1804fc7c183ed20704252830f

      - name: Unit tests
        run: npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 1

  scan-repo:
    name: CodeQL and Sonar scans
    permissions:
      security-events: write
    needs: unit-tests
    uses: ./.github/workflows/scan-repo.yml
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
    with:
      coverage-artifact: coverage
      coverage-run-id: ${{ github.run_id }}

  deploy-dev:
    uses: ./.github/workflows/_secure-pipeline-deploy.yml
    concurrency:
      group: deploy-to-dev
    permissions:
      id-token: write
      contents: read
    secrets:
      role_arn: ${{ secrets.DEV_GHA_ROLE_ARN }}
      artifact_bucket: ${{ secrets.DEV_ARTIFACT_BUCKET }}
      container_sign_kms_key: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      ecr_repository_test: ${{ secrets.DEV_ECR_TEST }}
      ecr_repository_traffic_test: ${{ secrets.DEV_ECR_TRAFFIC_TEST }}
      signing_profile: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
    with:
      environment: development

  deploy-build:
    uses: ./.github/workflows/_secure-pipeline-deploy.yml
    concurrency:
      group: deploy-to-build
    permissions:
      id-token: write
      contents: read
    secrets:
      role_arn: ${{ secrets.BUILD_GHA_ROLE_ARN }}
      artifact_bucket: ${{ secrets.BUILD_ARTIFACT_BUCKET }}
      container_sign_kms_key: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
      ecr_repository_test: ${{ secrets.BUILD_ECR_TEST }}
      ecr_repository_traffic_test: ${{ secrets.BUILD_ECR_TRAFFIC_TEST }}
      signing_profile: ${{ secrets.BUILD_SIGNING_PROFILE_NAME }}
    with:
      environment: build
