name: Post merge

on:
  push:
    branches:
      - main
  # pull_request: # temp

permissions: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: unit-tests-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    steps:
      - name: Setup Node
        uses: govuk-one-login/github-actions/node/install-dependencies@e34012cc1464012a5c99dafcea2e611cdb886434

      - name: Unit tests
        run: npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 1

  sonar-scan:
    name: Sonar scan
    runs-on: ubuntu-latest
    concurrency:
      group: sonar-${{ github.ref }}
      cancel-in-progress: true
    needs: unit-tests
    permissions:
      contents: read
    steps:
      - name: Run Sonar scan
        uses: govuk-one-login/github-actions/code-quality/sonarcloud@9d6ee027d0b9167dfc25e67124951956278bb585
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          coverage-artifact: coverage
          coverage-run-id: ${{ github.run_id }}

  codeql:
    name: CodeQL scan
    runs-on: ubuntu-latest
    concurrency:
      group: codeql-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      security-events: write
    steps:
      - name: Run CodeQL scan
        uses: govuk-one-login/github-actions/code-quality/codeql@f5362528578198e7851e96e0594f593beff0162e

  # there is still room to think about doing scan-repo instead here and in pre-merge
  # would mean running unit tests for no reason sometime tho on cron

  # deploy-dev:
  #   uses: ./.github/workflows/_secure-pipeline-deploy.yml
  #   permissions:
  #     id-token: write
  #     contents: read
  #   secrets:
  #     role_arn: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
  #     artifact_bucket: ${{ secrets.DEV_ARTIFACT_BUCKET }}
  #     container_sign_kms_key: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
  #     ecr_repository: ${{ secrets.DEV_ECR_REPOSITORY }}
  #     dynatrace_paas_token: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
  # with environment

  #   deploy-build:
  #   uses: ./.github/workflows/_secure-pipeline-deploy.yml
  #   permissions:
  #     id-token: write
  #     contents: read
  #   secrets:
  #     role_arn: ${{ secrets.BUILD_GH_ACTIONS_ROLE_ARN }}
  #     artifact_bucket: ${{ secrets.BUILD_ARTIFACT_BUCKET }}
  #     container_sign_kms_key: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
  #     ecr_repository: ${{ secrets.BUILD_ECR_REPOSITORY }}
  #     dynatrace_paas_token: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
  # with environment
