name: Scan repository

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      sonar_token:
        required: true
    inputs:
      coverage-artifact:
        required: false
        type: string
      coverage-run-id:
        required: false
        type: string
  schedule:
    - cron: '0 4 * * 1' # Every Monday at 4am

permissions: {}

concurrency:
  group: scan-repo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql:
    name: CodeQL scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Run CodeQL scan
        uses: govuk-one-login/github-actions/code-quality/codeql@46a0673dcb08419211a6c3ed0bbfa2eb6de812b3
        with:
          category: codeql

  sonar:
    name: Sonar scan
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.actor != 'dependabot[bot]' }}
    steps:
      - name: Run Sonar scan
        uses: govuk-one-login/github-actions/code-quality/sonarcloud@9d6ee027d0b9167dfc25e67124951956278bb585
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.sonar_token || secrets.SONAR_TOKEN }}
          coverage-artifact: ${{ inputs.coverage-artifact || null }}
          coverage-run-id: ${{ inputs.coverage-run-id || null }}
