name: Scan repository

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      sonar_token:
        required: true
  schedule:
    - cron: '0 4 * * 1' # Every Monday at 4am

permissions: {}

concurrency:
  group: scan-repo-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Collect test coverage
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
    uses: ./.github/workflows/run-unit-tests.yml

  sonar:
    name: Sonar scan
    runs-on: ubuntu-latest
    needs: coverage
    if: ${{ success() || needs.coverage.result == 'skipped' }}
    steps:
      - name: Run Sonar scan
        uses: govuk-one-login/github-actions/code-quality/sonarcloud@9a6a12e591fecbc651ae646166c644748f442bb9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.sonar_token || secrets.SONAR_TOKEN }}
          coverage-artifact: coverage
          coverage-run-id: ${{ github.run_id }}

  codeql:
    name: CodeQL scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Run CodeQL scan
        uses: govuk-one-login/github-actions/code-quality/codeql@46a0673dcb08419211a6c3ed0bbfa2eb6de812b3
        with:
          category: codeql
